# ONLYOFFICE DocumentServer with Mobile Editing Unlocked
#
# Multi-stage build:
#   Stage 1 (webapps-builder): compile the patched web-apps from source via grunt.
#   Stage 2 (runtime): take the official 9.2.1 image and swap in our built web-apps.
#
# The base image's web-apps directory contains compiled, minified, deploy-ready
# assets (sprite LESS files, packed app.js bundles, mobile webpack output, etc.)
# generated by ONLYOFFICE's grunt build. Earlier revisions of this Dockerfile
# COPY'd raw source into that directory, which broke nginx (missing sprites)
# and prevented any document from opening. The source must be *built* first.

# ----------------------------------------------------------------------------
# Stage 1: Build patched web-apps from source
# ----------------------------------------------------------------------------
# Node 18 matches ONLYOFFICE's canonical build env: their dev container uses
# Ubuntu 24.04's apt nodejs (18.x), and document-server-package's Makefile
# pkg-targets node18-linux-x64 for the runtime.
FROM node:18-bookworm AS webapps-builder

# Native deps required by the grunt plugin chain:
#   build-essential / python3 / pkg-config -> node-gyp for native modules
#   libpng / libjpeg / libgif / librsvg    -> imagemin, spritesmith
#   libcairo / libpango                    -> node-canvas (used by spritesmith)
RUN apt-get update && apt-get install -y --no-install-recommends \
        git \
        python3 \
        build-essential \
        pkg-config \
        libcairo2-dev \
        libpango1.0-dev \
        libpng-dev \
        libjpeg-dev \
        libgif-dev \
        librsvg2-dev \
    && rm -rf /var/lib/apt/lists/*

RUN npm install -g grunt-cli

# Fetch the sdkjs source file(s) that grunt-inline expects to find as a
# sibling of web-apps. Currently the only one referenced via ?__inline=true
# is common/device_scale.js. If a future ONLYOFFICE version adds more sdkjs
# inline references, grep the source: `grep -rho 'sdkjs/[^\"]*__inline=true' web-apps/apps`
# and add them here.
#
# SDKJS_COMMIT is supplied by build_image.sh from the superproject's pinned
# submodule SHA, so it always matches the DocumentServer version we're building.
ARG SDKJS_COMMIT
RUN test -n "$SDKJS_COMMIT" || (echo "ERROR: SDKJS_COMMIT build-arg is required" && exit 1) && \
    mkdir -p /build/sdkjs/common && \
    curl -fSL "https://raw.githubusercontent.com/ONLYOFFICE/sdkjs/${SDKJS_COMMIT}/common/device_scale.js" \
         -o /build/sdkjs/common/device_scale.js

COPY ./web-apps /build/web-apps
WORKDIR /build/web-apps/build

RUN npm install

# Default task builds: common (api/sdk/etc) + all five editors, each with
# desktop (main), mobile (Framework7-React webpack), embed, and forms where
# applicable. Output lands at /build/web-apps/deploy/web-apps/.
# --force matches ONLYOFFICE's own CI invocation (build_tools/scripts/build_js.py).
#
# PRODUCT_VERSION + BUILD_NUMBER are critical for the mobile editor build:
# the framework7-react webpack DefinePlugin replaces __PRODUCT_VERSION__ with
# `${PRODUCT_VERSION}.${BUILD_NUMBER}`. If PRODUCT_VERSION is unset, it falls
# back to the hardcoded string '6.2.0.123d' — which ENDS WITH 'd', which makes
# About.developVersion() return true, which makes the mobile editor request
# /sdkjs/develop/sdkjs/word/scripts.js (a dev-mode manifest that doesn't exist
# in deployed images). Result: mobile editor stuck on loading screen.
# Grunt's increment-build also honours these env vars when writing version
# metadata into JSON config files. Values match official 9.2.1 builds.
ENV NODE_ENV=production \
    PRODUCT_VERSION=9.2.1 \
    BUILD_NUMBER=8
RUN grunt --force --verbose

# Fail the build early if grunt silently produced incomplete output.
# These artifacts only exist if their respective build stages actually ran:
#   index.html               -> deploy-app-main renamed index.html.deploy
#   resources/css/app.css    -> LESS compilation succeeded
#   resources/img/iconsbig*  -> grunt-spritesmith ran
#   mobile/dist/js/          -> Framework7-React webpack build succeeded
#   apps/common/             -> shared common bundle was deployed
RUN test -f /build/web-apps/deploy/web-apps/apps/documenteditor/main/index.html \
 && test -f /build/web-apps/deploy/web-apps/apps/documenteditor/main/resources/css/app.css \
 && test -f /build/web-apps/deploy/web-apps/apps/documenteditor/main/resources/img/iconsbig.png \
 && test -d /build/web-apps/deploy/web-apps/apps/documenteditor/mobile/dist/js \
 && [ -n "$(ls -A /build/web-apps/deploy/web-apps/apps/documenteditor/mobile/dist/js)" ] \
 && test -d /build/web-apps/deploy/web-apps/apps/common \
 || (echo "ERROR: grunt build produced incomplete output" && \
     ls -la /build/web-apps/deploy/web-apps/apps/documenteditor/main/ && \
     ls -la /build/web-apps/deploy/web-apps/apps/documenteditor/mobile/ && \
     exit 1)

# Catch the framework7-react PRODUCT_VERSION fallback. If '6.2.0.123d' ends
# up baked into any mobile bundle, About.developVersion() will return true
# at runtime and the editor will try to load dev-mode SDK manifests that
# don't exist (stuck-on-loading-screen failure mode).
RUN if grep -rl '6\.2\.0\.123d' /build/web-apps/deploy/web-apps/apps/*/mobile/dist/ 2>/dev/null | grep .; then \
        echo "ERROR: webpack baked the dev fallback PRODUCT_VERSION into a mobile bundle." && \
        echo "PRODUCT_VERSION/BUILD_NUMBER env vars probably weren't set during grunt." && \
        exit 1; \
    fi

# grunt-inline silently swallows missing-file errors when grunt runs with
# --force. If our inline-source setup above didn't cover a referenced file,
# the resulting index.html will still contain literal <script src=...?__inline=true>
# tags pointing at files that don't exist at runtime, and editors will fail
# to load. Fail the build if any survived.
RUN if grep -l '__inline=true' /build/web-apps/deploy/web-apps/apps/*/main/index.html \
     /build/web-apps/deploy/web-apps/apps/*/main/index_loader.html \
     /build/web-apps/deploy/web-apps/apps/*/embed/index.html 2>/dev/null; then \
       echo "ERROR: grunt-inline failed to inline some files. Surviving __inline=true references:" && \
       grep -lr '__inline=true' /build/web-apps/deploy/web-apps/apps/ && \
       echo "" && \
       echo "Likely cause: a referenced file is not present at the build-time path." && \
       echo "Search for 'sdkjs/...__inline=true' references in web-apps source and add to the curl step." && \
       exit 1; \
    fi

# ----------------------------------------------------------------------------
# Stage 2: Runtime image
# ----------------------------------------------------------------------------
FROM onlyoffice/documentserver:9.2.1

LABEL maintainer="Peter von Kaenel"
LABEL description="ONLYOFFICE DocumentServer 9.2.1 with mobile editing patches"

# Overlay our patched web-apps on top of the base image's web-apps.
#
# Why overlay instead of rm -rf + COPY: the .deb that ships in the base image
# adds a small number of files that the web-apps grunt build does NOT produce
# (notably apps/api/documents/api.js.tpl, which the runtime entrypoint cp's
# to apps/api/documents/api.js, plus apps/common/main/resources/img/doc-formats/formats@2.5x.svg).
# A destructive replace deletes those and breaks the document server at startup.
#
# COPY's merge semantics give us what we want: every file produced by grunt
# overwrites the base image's version (so all our patches land), while
# non-grunt artifacts from the .deb stay intact.
#
# --chown applies ownership at copy time in the same layer. Without it, a
# separate `chown -R ds:ds` RUN step would create a second full-size copy
# of web-apps in a new overlayfs layer (changing ownership rewrites every
# file metadata entry), roughly doubling the runtime image size.
COPY --from=webapps-builder --chown=ds:ds \
     /build/web-apps/deploy/web-apps \
     /var/www/onlyoffice/documentserver/web-apps

EXPOSE 80 443

CMD ["/app/ds/run-document-server.sh"]
